spring.application.name=fake-store-auth-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES}
app.cookie.refresh-expiration-seconds=${APP_COOKIE_REFRESH_EXPIRATION_SECONDS}
app.cookie.same-site=${APP_COOKIE_SAME_SITE}
app.cookie-secure=${APP_COOKIE_SECURE}
app.cors.allowed-origins=${ALLOWED_ORIGINS}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true

