spring.application.name=fake-store-auth-service
spring.config.import=aws-parameterstore:/config/auth/
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.private-key=
jwt.public-key=
jwt.expiration-minutes=
app.cookie.refresh-expiration-seconds=
app.cookie.same-site=
app.cookie-secure=
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
server.port=${SERVER_PORT:8081}